//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fehrist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_IMAGES
    {
        public int IMAGEID { get; set; }
        public string TI_PATH { get; set; }
        public Nullable<int> TASKID { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
    
        public virtual TASK TASK { get; set; }
    }
}
