//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fehrist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TASK()
        {
            this.TASK_IMAGES = new HashSet<TASK_IMAGES>();
        }
    
        public int TASKID { get; set; }
        public Nullable<int> ACCOUNTID { get; set; }
        public string T_TITLE { get; set; }
        public string T_DESC { get; set; }
        public string T_STATUS { get; set; }
        public string T_COLOR { get; set; }
        public string T_DUE_DATE_TIME { get; set; }
        public string T_ADDED_DATE_TIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_IMAGES> TASK_IMAGES { get; set; }
    }
}
